name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: D3rHase/ssh-command-action@v0.2.1
      with:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USERNAME }}
        PRIVATE_SSH_KEY: ${{ secrets.KEY }}
        PORT: ${{ secrets.PORT }}
        COMMAND: "cd pause && ./deploy.sh"
